export const API_BASE_URL = 'https://ushers-registration-backend.onrender.com/api/v1'
export const ATTENDEES_QUERY_KEY = 'attendees'
export const ATTENDEE_QUERY_KEY = 'attendee'
export const ATTENDEES_BY_HIERARCHY_QUERY_KEY = 'attendee_hierarchy'
export const ATTENDEES_BY_STATUS_QUERY_KEY = 'attendee_status'
export const ATTENDANCE_QUERY_KEY = 'attendance'
export const CALENDAR_QUERY_KEY = 'calendar'